FROM mcr.microsoft.com/devcontainers/base:bullseye
COPY --from=denoland/deno:bin-2.0.4 /deno /usr/local/bin/deno

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends <your-package-list-here>
